kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: personal-cluster
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./var/grafana
    containerPath: /var/personal-cluster/grafana
  - hostPath: ./var/redis
    containerPath: /var/personal-cluster/redis
  - hostPath: ./var/postgres
    containerPath: /var/personal-cluster/postgres
  - hostPath: ./var/scylla
    containerPath: /var/personal-cluster/scylla
  extraPortMappings:
  # dashboard
  - containerPort: 30843
    hostPort: 8443
  # grafana
  - containerPort: 30300
    hostPort: 3000
  # redis
  - containerPort: 30379
    hostPort: 6379
  # postgres
  - containerPort: 30432
    hostPort: 5432
  # scylla
  - containerPort: 30042
    hostPort: 9042
  - containerPort: 31000
    hostPort: 10000
