apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scylla
  labels:
    app: scylla
spec:
  resources:
    requests:
      storage: "100Mi"
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: scylla
