apiVersion: v1
kind: Service
metadata:
  name: scylla
  labels:
    app: scylla
spec:
  type: NodePort
  selector:
    app: scylla
  ports:
  - port: 9042
    nodePort: 30042
    name: cqlsh
  - port: 10000
    nodePort: 31000
    name: alternator
