apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- deployment.yaml
- service.yaml

images:
- name: grafana
  newName: grafana/grafana-oss
  newTag: "9.5.1"
