apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  resources:
    requests:
      storage: "100Mi"
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: grafana
