apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  resources:
    requests:
      storage: "100Mi"
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: postgres
