apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- persistentvolume.yaml
- persistentvolumeclaim.yaml

images:
- name: redis
  newName: redis
  newTag: "7.0"
