apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  labels:
    app: redis
spec:
  resources:
    requests:
      storage: "100Mi"
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: redis
